# Browser to use: chrome | firefox | edge
browser=edge

# Base URL
baseUrl=https://www.coursera.org

# Implicit wait (seconds)
implicitWait=10

# Page load timeout (seconds)
maxWaitTime=30


# Excel output file path
excelOutputPath=src/test/resources/testdata/CourseData.xlsx